version: 1
allow:
  depOnAnyVendor: false

exclude:
  - .idea
  - vendor
  - cmd
  - resources
  - registry

excludeFiles:
  - "^.*_test\\.go$"

vendors:
  sdl:
    in: github.com/veandco/go-sdl2/sdl
  sdl-ttf:
    in: github.com/veandco/go-sdl2/ttf
  sdl-img:
    in: github.com/veandco/go-sdl2/img
  loader-yaml:
    in: gopkg.in/yaml.v2

components:
  main:
    in: .
  registry:
    in: registry
  system:
    in: system

  engine:
    in: engine
  engine_event:
    in: engine/event
  engine_control:
    in: engine/control
  engine_lib:
    in: engine/lib
  engine_lib_render:
    in: engine/lib/render
  engine_entity:
    in: engine/entity
  engine_editor:
    in: engine/editor
  engine_loader:
    in: engine/loader
  engine_collider:
    in: engine/collider
  engine_collision:
    in: engine/collision

  shared_ui:
    in: shared/ui

  editor:
    in: editor
  editor_components:
    in: editor/components

  game:
    in: game
  game_entities:
    in: game/entities
  game_component:
    in: game/entities/components/**
  game_const:
    in: game/gm

  generated:
    in: generated
  utils:
    in: utils

commonComponents:
  - generated
  - utils

deps:
  engine_lib:
    canUse:
      - sdl
      - sdl-ttf
      - sdl-img

  engine_lib_render:
    mayDependOn:
      - engine
      - engine_lib
      - engine_event
    canUse:
      - sdl
      - sdl-ttf
      - sdl-img

  engine_event:
    mayDependOn:
      - engine
    canUse:
      - sdl

  engine_control:
    mayDependOn:
      - engine
      - engine_event
    canUse:
      - sdl

  engine_entity:
    mayDependOn:
      - engine

  engine_collision:
    mayDependOn:
      - engine

  engine_collider:
    mayDependOn:
      - engine
      - engine_collision

  engine_editor:
    mayDependOn:
      - engine
      - engine_event

  engine_loader:
    canUse:
      - loader-yaml

  editor:
    mayDependOn:
      - engine

  editor_components:
    mayDependOn:
      - engine

  game:
    mayDependOn:
      - engine
      - engine_entity
      - engine_event
      - game_entities
      - game_const

  game_entities:
    mayDependOn:
      - engine
      - engine_entity
      - game_component
      - game_const

  game_component:
    mayDependOn:
      - engine
      - engine_entity
      - game_component
      - game_const

  shared_ui:
    mayDependOn:
      - engine

  main:
    mayDependOn:
      - game
      - registry
      - system
      - engine
      - engine_event
      - game

