version: 1
allow:
  depOnAnyVendor: true

exclude:
  - vendor
  - cmd

excludeFiles:
  - "^.*_test\\.go$"

components:
  consts:
    in: consts

  innerDI:
    in: internal/di
  innerEngine:
    in: internal/engine/**
  innerFrames:
    in: internal/frames
  innerUtils:
    in: internal/utils

  galx:
    in: galx

  scopeEditor:
    in: scope/editor/**
  scopeGame:
    in: scope/game/**
  scopeShared:
    in: scope/shared/**

  cfg:
    in: cfg
  bootstrap:
    in: .

commonComponents:
  - consts

deps:
  innerDI:
    anyVendorDeps: true
    anyProjectDeps: true

  bootstrap:
    mayDependOn:
      - innerDI
      - innerEngine
      - innerFrames
      - innerUtils
      - cfg

  innerEngine:
    mayDependOn:
      - galx
      - innerUtils
      - innerEngine

  scopeEditor:
    mayDependOn:
      - galx

  scopeGame:
    mayDependOn:
      - galx

  scopeShared:
    mayDependOn:
      - galx
