// autogenerated DO NOT EDIT

package vulkan

import (
	_ "embed"

	"github.com/vulkan-go/vulkan"
)

// all common shaders include as byte code inside engine binary
// custom shaders will be loaded from assets, and compile on the fly

// todo: write auto. generator

const (
	shaderIDTriangleFrag shaderModuleID = "triangle.frag"
	shaderIDTriangleVert shaderModuleID = "triangle.vert"
)

var (
	//go:embed shader/compiled/triangle.frag.spv
	commonShaderTriangleFrag []byte

	//go:embed shader/compiled/triangle.vert.spv
	commonShaderTriangleVert []byte
)

var shadersByteCode = map[shaderModuleID][]byte{
	shaderIDTriangleFrag: commonShaderTriangleFrag,
	shaderIDTriangleVert: commonShaderTriangleVert,
}

var shadersType = map[shaderModuleID]vulkan.ShaderStageFlagBits{
	shaderIDTriangleFrag: vulkan.ShaderStageFragmentBit,
	shaderIDTriangleVert: vulkan.ShaderStageVertexBit,
}
