name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.14.x]
        os: [ubuntu-latest]
    steps:
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: install sdl and linters
        run:
          - sudo apt install libsdl2{,-image,-mixer,-ttf,-gfx}-dev
          - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0

      - name: checkout
        uses: actions/checkout@v2

      - name: arch
        run: make arch

      - name: test
        run: make test

      - name: lint
        run: make lint